name: Flutter Build & Release APK

on:
  push:
    branches: [ main ]
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter --version

      - run: flutter pub get     

      - run: flutter build apk --release

      # 👉 Tạo timestamp
      - name: Set timestamp
        run: echo "TIME=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      # 👉 Rename file APK
      - name: Rename APK
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk \
             build/app/outputs/flutter-apk/pet-tag-pro-$TIME.apk
      
      - uses: actions/upload-artifact@v4
        with:
          name: pet-tag-pro-$TIME
          path: build/app/outputs/flutter-apk/pet-tag-pro-$TIME.apk   
     
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/app/outputs/flutter-apk/pet-tag-pro-release-$TIME.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
